// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS8Q1gbOsUGMwphtjN9hKXXLo024_V3Y0',
    appId: '1:168937282821:web:a0d377ed263a46202d6b6c',
    messagingSenderId: '168937282821',
    projectId: 'guichetier-224b2',
    authDomain: 'guichetier-224b2.firebaseapp.com',
    storageBucket: 'guichetier-224b2.appspot.com',
    measurementId: 'G-E2LR7X09RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb29YKvTV4A53fxlMXkmX2lvDTKfFJ0eY',
    appId: '1:168937282821:android:c6e892839e9057012d6b6c',
    messagingSenderId: '168937282821',
    projectId: 'guichetier-224b2',
    storageBucket: 'guichetier-224b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoUZuKOJLqxayzoduSB5vnQX6vJVzhiD4',
    appId: '1:168937282821:ios:bdac8dab267de71f2d6b6c',
    messagingSenderId: '168937282821',
    projectId: 'guichetier-224b2',
    storageBucket: 'guichetier-224b2.appspot.com',
    iosClientId: '168937282821-3k56hk20r1bt2l5m83up51opgmmc4rd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.guichetier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoUZuKOJLqxayzoduSB5vnQX6vJVzhiD4',
    appId: '1:168937282821:ios:bdac8dab267de71f2d6b6c',
    messagingSenderId: '168937282821',
    projectId: 'guichetier-224b2',
    storageBucket: 'guichetier-224b2.appspot.com',
    iosClientId: '168937282821-3k56hk20r1bt2l5m83up51opgmmc4rd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.guichetier',
  );
}
